language: c

addons:
  apt:
    packages:
      - lcov

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./tests/test_jsmn_parser
  - make lcov
  
after_success:
  - codecov -t 37e1e81f-12be-4e55-add0-dcfccf0edee1 -X lcov
